# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Convenient_Foodie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseCore'
  pod 'FirebaseMessaging'

  target 'Convenient_FoodieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Convenient_FoodieUITests' do
    # Pods for testing
  end

 

end
